### ISSUE TITLE
Upgrade to font-awesome 4.4

### ISSUE THREAD

**Issue by kristianperkins** [donbeave/grails-font-awesome#3]
There is [a bunch of cool icons in font-awesome 4.4](https://fortawesome.github.io/Font-Awesome/whats-new/) that would be great to include in this plugin.  Please upgrade the version of font-awesome to 4.4.

**Comment by donbeave** [comment]
Done: https://github.com/donbeave/grails-font-awesome/commit/6508055d9b70980b61b8f63e2ef8163d06b9c88c

**Comment by kristianperkins** [comment]
Awesome!  Thanks.

**Comment by donbeave** [comment]
No prob.
